[build-system]
requires = [ "setuptools>=68.0",]
build-backend = "setuptools.build_meta"

[project]
name = "background-music"
version = "2.5.0"
description = "Schedule music to play in the background"
readme = "README.md"
license = "MIT"
requires-python = ">=3.8"
dependencies = [ "pygame", "inotify_simple",]

[project.scripts]
bgmus = "background_music.main:main"

[tool.setuptools]
packages = [ "background_music",]
